tools/urls.py
from django.conf.urls import patterns, url

from tools import views

urlpatterns = patterns( '',
    url( r'^$', views.index, name = 'index' ),

    url( r'^register.html', views.register, name = 'register' ),
    url( r'^login.html', views.get_login_page, name = 'login' ),
    url( r'^me.html', views.me, name='userpage' ),
    url( r'^createsharezone.html', views.createShareZone, name = 'createsz' ),
    url( r'^zoneAll.html', views.zoneAll, name='zoneAll' ),
	url( r'^zone.html', views.zone, name='zone' ),
    url( r'^me.html', views.me, name='confirmReservation' ),
    url( r'^changeprefs.html', views.changeprefs, name='changeprefs' ),
    url( r'^adminChangePrefs.html', views.adminChangePrefs, name='adminChangePrefs'),
    url( r'^csview.html', views.viewCommunityShed, name='viewCommunityShed' ),
    url( r'^toolview.html', views.toolView, name='toolView' ),
    url( r'^createTool.html', views.createTool, name='createTool' ),
    url( r'^szadmin.html', views.szAdmin, name='szadmin' ),
    url( r'^uadmin.html', views.administrateUser, name='administrateUser' ),
    url( r'^logout.html', views.logout_view, name='logout' ),
    url( r'^admin.html', views.admin, name='adminpage' ),
    url( r'^approveUser.html', views.approveUser, name='approveUser' ),
    url( r'^borrowTool.html', views.showBorrowTool, name='showBorrowTool' ),
    url( r'^createcs.html', views.createcs, name='createcs' ),
    url( r'^myTools.html', views.toolAll, name='alltools'),
    url( r'^confirm.html', views.confirm, name='confirmation'), 
    url( r'^message.html', views.messagepg, name='message'),
    url( r'^statistics.html', views.getStats, name='getStats'),
    #url( r'^alltools.html', views.me, name='alltools' ),

    url( r'^notifications.html', views.getNotifications, name='notifications' ),
    url( r'^mysheds.html', views.csadmin, name='mycs' ),
    url( r'^findTool.html', views.findTool, name='findTool' ),
)

toolshare/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url( r'^admin/', include( admin.site.urls ) ),
    url( r'^tools/', include( 'tools.urls', namespace = 'tools' ) ),
)

tools/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
import hashlib
import uuid
    
class UserData( models.Model ): 
    user = models.ForeignKey( User )
    
    birthday = models.DateField()
    isMale = models.BooleanField()
    location = models.CharField( max_length = 200 ) 
    rating = models.FloatField( default = 0 )
    numRatings = models.IntegerField( default = 0 )
    shareZone = models.ForeignKey( 'ShareZone' )
    house = models.ForeignKey( 'CommunityShed' )

    def getTools(self):
        tools = Tool.objects.filter(owner = self, status = 1)
        return tools
    
    def getRating(self):
        rating = self.rating
        if rating < 0.001:
            rating = 'Unrated'
        return rating
        
    def updateUser(self,firstName,lastName,password,email,location,birthday):
        self.user.first_name = firstName
        self.user.last_name = lastName
        self.user.set_password(password)
        self.user.email = email
        self.user.username = email   
        self.location = location
        self.birthday = birthday
        self.user.save()
        self.save()

    
    def __str__( self ):
        return self.user.first_name + ' ' + self.user.last_name

class Notification( models.Model ):
    to = models.ForeignKey( 'UserData', related_name = 'recvMsg' )
    sender = models.ForeignKey( 'UserData', related_name = 'sentMsg' )
    date = models.DateTimeField()
    message = models.TextField()
    isNew = models.BooleanField( default = True )

class Reservation( models.Model ):
    startDate = models.DateTimeField()
    endDate = models.DateTimeField()
    tool = models.ForeignKey( 'Tool' )
    borrower = models.ForeignKey( 'UserData' )
    status = models.IntegerField()
    comments = models.TextField( blank = True )

class ToolType( models.Model ):
    type = models.CharField( max_length = 200 )
    
    def __str__( self ):
        return self.type
    
class Tool (models.Model):
    name = models.CharField( max_length = 200 )
    owner = models.ForeignKey( UserData, related_name = 'ownedTool' )
    toolType = models.ForeignKey( 'ToolType' )
    defaultLocation = models.ForeignKey( 'CommunityShed', related_name = 'storedTool' )
    currentLocation = models.ForeignKey( 'CommunityShed', related_name = 'heldTool' )
    manufacturer = models.CharField( max_length = 200 )
    condition = models.IntegerField()
    additionalDetails = models.TextField()
    isRestricted = models.BooleanField()
    status = models.IntegerField( default = 1 )
        
    def __str__( self ):
        return self.name

class ShareZone( models.Model ):

    name = models.CharField( max_length = 200 )
    restrictedAge = models.IntegerField()
    isActive = models.BooleanField()

    def getActiveUsers(self):
        users = UserData.objects.filter(shareZone = self, user__is_active = True)
        return users
    
    def getInactiveUsers(self):
        users = UserData.objects.filter(shareZone = self, user__is_active = False)
        return users
    #This is a change
    
    def getAllCSs(self):
        cSheds = CommunityShed.objects.filter(shareZone = self)
        return cSheds
        
    def getCSs(self):
        cSheds = CommunityShed.objects.filter(shareZone = self, isHouse = False)
        return cSheds
        
    def getTools(self):
        cSheds = self.getAllCSs()
        tools=[]
        for shd in cSheds:
            tools += Tool.objects.filter(defaultLocation = shd, status = 1)
        return tools
        
    def getAllTools(self):
        cSheds = self.getAllCSs()
        tools=[]
        for shd in cSheds:
            tools += Tool.objects.filter(defaultLocation = shd)
        return tools
    
    def getAvailableTools( self ):
        tools = Tool.objects.filter( defaultLocation__shareZone = self, status = 1 )
        aTools = []
        for t in tools:
            if t.defaultLocation == t.currentLocation:
                aTools.append( t )
        return aTools

    def getUnavailableTools( self ):
        tools = Tool.objects.filter( defaultLocation__shareZone = self, status = 1 )
        uTools = []
        for t in tools:
            if t.defaultLocation != t.currentLocation:
                uTools.append( t )
        return uTools
       
    def __str__( self ):
        return self.name
        
        
class CommunityShed( models.Model ):
    name = models.CharField( max_length = 200 ) 
    maxNumberOfTools = models.IntegerField()
    numberOfTools = models.IntegerField()
    location = models.CharField( max_length = 200 )
    shareZone = models.ForeignKey( 'ShareZone' )
    isHouse = models.BooleanField()
    
    def getDefTools(self):
        tools = Tool.objects.filter(defaultLocation = self, status = 1)
        return tools
        
    def getCurTools(self):
        tools = Tool.objects.filter(currentLocation = self, status = 1)
        return tools    
        
        
    def __str__( self ):
        return self.name

tools/views.py
import datetime
#import pytz

from django.db.models import F
from django.utils import timezone
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User, Group
from django.contrib.auth.decorators import login_required

from tools.models import UserData, ShareZone, CommunityShed
from tools.models import Reservation, Tool, ToolType, Notification

def index( request ):
    if request.user.is_authenticated():
        #See if the user has a UserData and isn't just an admin
        try:
            u = UserData.objects.get( user = request.user )
            return redirect ( "/tools/me.html" )
        except:
            pass
    return render( request, "tools/index.html" )

def name_invalid( name ):
    return any( char.isdigit() for char in name )

def email_invalid( email ):
    from django.core.validators import validate_email
    from django.core.exceptions import ValidationError
    try:
        validate_email( email )
        return False
    except ValidationError:
        return True

def password_invalid( password ):
    return len( password ) < 10

def birthday_invalid( birthday ):
    birthYear = int( birthday[0:4] )
    birthMonth = int( birthday[5:7] )
    birthDay = int( birthday[8:] )
    try:
        dateOfBirth = datetime.date( birthYear, birthMonth, birthDay )
        return datetime.date( birthYear, birthMonth, birthDay ) > datetime.date.today()
    except:
        return True


def state_invalid( state ):
    state = state.upper()
    states = {'AL', 'AK', 'AS', 'AZ', 'AR_', 'CA', 'CO', 'CT', 'DE', 'DC', 'FM', 'FL',
        'GA', 'GU', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MH', 'MD',
        'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC',
        'ND', 'MP', 'OH', 'OK', 'OR', 'PW', 'PA', 'PR', 'RI', 'SC', 'TN', 'TX', 'UT',
        'VT', 'VI', 'VA', 'WA', 'WV', 'WI', 'WY', 'AA', 'AP'
    }
    return state not in states

def get_num_notifications( userData ):
    return len( Notification.objects.filter( to = userData, isNew = True ) )

def get_login_context( user ):
    context = {}
    if user.is_authenticated():
        context['loggedin'] = True

        # check if the user is in charge or any ShareZones
        szAdminGroups = []
        szAdminGroupNames = []
        for sz in ShareZone.objects.all():
            szAdminGroupNames.append( sz.name[0:20] + '_admins' )
        for szagn in szAdminGroupNames:
            szAdminGroups.append( Group.objects.get( name = szagn ) )
        context['groups'] = szAdminGroupNames

        for g in szAdminGroups:
            if g in user.groups.all():
                context['admin'] = True

        userData = UserData.objects.get( user = user )

        # Check if the user is in charge of any Community Sheds
        csAdminGroups = []
        for cs in CommunityShed.objects.filter( shareZone = userData.shareZone ):
            if 'house' not in cs.name:
                # This community shed isn't a house! Oh me oh my!
                csagn = cs.shareZone.name[0:20] + '_' + cs.name[0:40] + '_admins'
                csAdminGroups.append( Group.objects.get( name = csagn ) )
        for g in csAdminGroups:
            if g in user.groups.all():
                context['csadmin'] = True

        context['numNotifs'] = get_num_notifications( userData )
        context['userData'] = userData
    return context
   
# David is done with this function and all above it.
def register( request ):
    context = get_login_context( request.user )
    context['sharezones'] = ShareZone.objects.filter(isActive = True)

    if request.method == 'POST':
        for i in request.POST:
            context[i] = request.POST[i].strip()

        firstName   = context['fname']
        lastName    = context['lname']
        email       = context['email']
        password    = context['password']
        password_confirm = context['password_confirm']
        birthday    = context['bday']
        sex         = context['sex']
        address     = context['address']
        state       = context['state']
        city        = context['city']

        valid = True

        # Determine if the user is creating a new ShareZone or not
        if 'shareZone' in context:
            shareZone   = context['shareZone']
            context['oldsz'] = 'join'
            joining = True
        elif 'newSZName' in context:
            newSZName = context['newSZName']
            newSZName = newSZName + " @ " + context['newSZZip']
            newSZAge = context['newSZAge']
            context['oldsz'] = 'create'
            joining = False
        else:
            context['szerror'] = "You must either join a ShareZone or create a new one"
            valid = False

        #make sure the password, zip code, address, birthday, etc are all valid
        if name_invalid( firstName ):
            value = False
            context['fname_error'] = 'No numbers allowed in first name'
        if name_invalid( lastName ):
            valid = False
            context['lname_error'] = 'No numbers allowed in last name'
        if email_invalid( email ):
            valid = False
            context['email_error'] = 'Invalid email address'
        if password_invalid( password ):
            valid = False
            context['password_error'] = 'Passwords must be at least 10 characters'
        if birthday_invalid( birthday ):
            valid = False
            context['bday_error'] = 'You must have been born to use this site'
        if state_invalid( state ):
            valid = False
            context['state_error'] = 'Please enter the postal code of a US state'
        if name_invalid( city ):
            valid = False
            context['city_error'] = 'Cities cannot have numbers'
        if password != password_confirm:
            valid = False
            context['password_different_error'] = 'Please make sure that your passwords are the same'

        if valid:
            #create the Django authentication user
            try:
                user = User.objects.create_user( username = email, email = email, password = password )
            except:
                context['email_error'] = 'Sorry, this e-mail address is already taken'
                return render( request, 'tools/register.html', context )
            user.first_name = firstName
            user.last_name = lastName
            user.is_active = False
            user.save()
            
            #create the ToolShare User
            birthYear = int( birthday[0:4] )
            birthMonth = int( birthday[5:7] )
            birthDay = int( birthday[8:] )

            isMale = False;
            if sex == 'male':
                isMale = True;
            
            if joining: 
                selectedShareZone = ShareZone.objects.get( name = shareZone )
            else:
                selectedShareZone = ShareZone.objects.create( name = newSZName, restrictedAge = newSZAge, isActive = False )
                selectedShareZone.save()
 
                newGroupName =  selectedShareZone.name[0:20] + '_admins'
                newGroup = Group.objects.create( name = newGroupName )
                newGroup.save()
        
                #add all the superadmins to this group
                superAdmins = User.objects.filter( is_staff = True )
                for sa in superAdmins:
                    sa.groups.add( newGroup )
                    sa.save()

            nullZones = ShareZone.objects.filter( name = 'DANGERZONE')
            if len(nullZones) == 0:
                nullZone = ShareZone.objects.create( name = 'DANGERZONE', restrictedAge = 0, isActive = False )
                nullZone.save()
                nZoneAdminName = nullZone.name[0:20] + '_admins'
                nZoneAdminGroup = Group.objects.create( name = nZoneAdminName )
                nZoneAdminGroup.save() 

            userData = UserData( user = user, birthday = datetime.date( birthYear, birthMonth, birthDay ), location = address + ' ' + city + ' ' + state, isMale = isMale )
            
            #If there's no one in this ShareZone, the user should become the admin
            usersInShareZone = UserData.objects.filter( shareZone = selectedShareZone )
           
            if not usersInShareZone:
                #make the user the ShareZone's admin
                szAdminName = selectedShareZone.name[0:20] + '_admins'
                szAdminGroup = Group.objects.get( name = szAdminName )
                szAdminGroup.user_set.add( user )
                user.is_active = True
                szAdminGroup.save()
                
            userData.shareZone = selectedShareZone
                
            #create a new CommunityShed to serve as the user's house
            csName = user.first_name +'_' +user.last_name +'_house'
            #alreadyExistingHouses = CommunityShed.objects.filter( name == csName )
            house = CommunityShed( name = csName, maxNumberOfTools = 100, location = userData.location, shareZone = selectedShareZone )
            house.isHouse = True
            house.numberOfTools = 0
            house.save()
            
            userData.house = house
            
            #create a new permissions group for the user's house
            csPermGroupName = house.shareZone.name[0:20] +'_' +house.name[0:40] +'_admins'
            houseGroup = Group.objects.create( name = csPermGroupName )
            houseGroup.save()
            houseGroup.user_set.add( user )
            
            user.save()
            userData.save()
            house.save()
            houseGroup.save()
            
            return redirect( "/tools/login.html", context )
        else:
            return render( request, "tools/register.html", context )
    return render( request, "tools/register.html", context )

@login_required
def changeprefs( request ):

tools/templates/tools/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
  <title>{% block title %}ToolShare{% endblock %}</title>
</head>

<body>
  <div class="navbar">
    {% block navbar %}
      {% if loggedin %}
        <div class="left">
          ToolShare
          <a href="{% url 'tools:zone' %}">My ShareZone</a>
          <a href="{% url 'tools:alltools' %}">My Tools</a>
          {% if csadmin %}
            <a href="{% url 'tools:mycs' %}">My Community Sheds</a>
          {% endif %}
        </div>

        <div class="right">
          {% if admin %}
            <a href="{% url 'tools:adminpage' %}">Admin</a>
          {% endif %}
          <a href="{% url 'tools:notifications' %}">Notifications: {{ numNotifs }}</a>
          <a href="{% url 'tools:userpage' %}">Profile</a>
          <a href="{% url 'tools:logout' %}">Logout</a>
        </div>
      {% else %}
        <div class="left">
          ToolShare
        </div>
        <div class="right">
          <a href="{% url 'tools:register' %}">Register</a>
        </div>
      {% endif %}
      
    {% endblock %}
  </div>

  <div id="content">
    <br/><br/>
    {% block content %}{% endblock %}
  </div>
</body>
</html>
      

tools/templates/tools/createsharezone.html
{% extends "tools/base.html" %}

{% block title %}Create a ShareZone{% endblock %}

{% block content %}
<h1>Create a new ShareZone</h1>

<div class="display createsz-form">
<form action="{% url 'tools:createsz' %}" method="post">
  {% csrf_token %}
  <p>Name:<br>
  <input type="text" name="sname" required>
  
  <p>Restricted Age:<br>
  <input value="10" type="age" name="rage" min="0" max="120" required>
  
  <p><input type="submit" value="Create">
</form></div>
{% endblock %}

tools/templates/tools/findTool.html
{% extends "tools/base.html" %}

{% block title %}Find a Tool{% endblock %}

{% block content %}
<div class="container">
  <h1>Find a Tool</h1>

  <div class="row">

    <div class="col-md-4">
      <input type="button" onclick="showAdvancedOptions()" value="Show Advanced Options" id="sho-btn" />
      <input type="button" onclick="hideAdvancedOptions()" value="Hide Advanced Options" id="hid-btn" class="hidden" />
      <form action="{% url 'tools:findTool' %}" method="post">
        {% csrf_token %}
        Tool condition is 
        <select name="condCmpFnc">
          <option value=">">greater than</option>
          <option value="=">exactly</option>
          <option value="<">less than</option>
        </select>
        <input type="number" name="cond" min="1" max="5" required/>
        <br /><br/>

        <div class="hidden" id="advanced">
          Tool name: <input type="text" name="toolname" />
          <br/><br/>

          Tool's type:
          <select name="type">
            <option value="-1">Any type</option>
            {% for type in types %}
            <option value="{{ type.id }}">{{ type.type }}</option>
            {% endfor %}
          </select>
          <br/><br/>

          Tool's location:
          <select name="loc">
            <option value="-1">Any location</option>
            {% for cs in sheds %}
            <option value="{{ cs.id }}">{{ cs.name }}</option>
            {% endfor %}
          </select>
          <br/><br/>

          Owner:
          <select name="own">
            <option value="-1">Any owner</option>
            {% for user in users %}
            <option value="{{ user.id }}">{{ user }}</option>
            {% endfor %}
          </select>
          <br/><br/>

          Show tools that are: <br/>
          <input type="checkbox" name="rest" value="True" checked>Restricted<br/>
          <input type="checkbox" name="unrest" value="True" checked>Not restricted<br/>

          <br/><br/>
        </div>
        <input type="submit" name="action" value="Submit" />
      </form>
    </div>

    <div class="col-md-8">
      {% for tool in results %}
      <div class="row outline">
        <div class="col-md-6">
          <b>Name:</b> {{ tool.name }}<br/>
          <b>Location:</b> {{ tool.currentLocation }}</br>
          <b>Type:</b> {{ tool.toolType }}</br>
          <b>Owner: </b> {{ tool.owner }}</br>
          <b>Available: </b> {% if tool.defaultLocation == tool.currentLocation %}Yes{% else %}No{% endif %}<br/>
        </div>

        <div class="col-md-6">
          <div class="row">
            <form action="{% url 'tools:showBorrowTool' %}" method="post">
              {% csrf_token %}
              <input type="hidden" name="toolID" value="{{ tool.id }}" />
              <input type="submit" name="action" value="Reserve" />
            </form>

          </div>

          <div class="row">
            <form action="{% url 'tools:toolView' %}" method="post">
              {% csrf_token %}
              <input type="hidden" name="toolID" value="{{ tool.id }}" />
              <input type="submit" name="action" value="View" />
            </form>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>

<script>
  function showAdvancedOptions() {
    document.getElementById( 'advanced' ).className = '';
    document.getElementById( 'sho-btn' ).className = 'hidden';
    document.getElementById( 'hid-btn' ).className = '';
  }

  function hideAdvancedOptions() {
    document.getElementById( 'advanced' ).className = 'hidden';
    document.getElementById( 'sho-btn' ).className = '';
    document.getElementById( 'hid-btn' ).className = 'hidden';
  }
</script>

{% endblock %}

tools/templates/tools/me.html
{% extends "tools/base.html" %}

{% block title %}{{userData.user.first_name }} {{ userData.user.last_name }}{% endblock %}

{% block content %}
<h1>User Page</h1>


<h2>Name</h2>
<div class="display p-info name">{{ userData.user.first_name }} {{ userData.user.last_name }}</div>

<h2>Email</h2>
<div class="display p-info email">{{ userData.user.email }}</div>

<h2>Birthday</h2>
<div class="display p-info bDay">{{ userData.birthday }}</div>

<h2>Gender</h2>
{% if userData.isMale %}
    <div class="display p-info gender">Male</div>
{% else %}
    <div class="display p-info gender">Female</div>
{% endif %}

<h2>Location</h2>
<div class="display p-info loc">{{ userData.location }}</div>

<h2>Average rating</h2>
<div class="display p-info rating">{{ rating }}</div>

<h2>ShareZone</h2>
<div class="display p-info zones">{{ userData.shareZone.name }}</div>


<h2>Tools</h2>
{% for tl in Tools %}
	<div class="display p-info tools">{{tl}}</div>
{% endfor %}

<br/><div class="display p-info maketool"><a href="/tools/createTool.html">Create a new Tool</a></div>

<h2>Unfinished Reservations</h2>
{% for reserve in openReserves %}
<div class="display p-info unfinished">{{ reserve.borrower }} wants to borrow  {{ reserve.tool.name }} from
    {{ reserve.startDate }} to {{reserve.endDate }}.
    <form action="{% url 'tools:confirmReservation' %}" method="POST">
      {% csrf_token %}
      <input type="hidden" name="reservID" value="{{ reserve.id }}">
      <br><input type="submit" name="action" value="Approve"> <input type="button" onclick="showField()" value="Deny">
      <div id="denyField"></div>
    </form>
    </div>
{% endfor %}
<br><div class="display p-info change"><a href="{% url 'tools:changeprefs' %}">Edit profile</a></div>

<script>
  function showField() {
    document.getElementById( 'denyField' ).innerHTML = 'Why are you denying this borroying request?<br/><textarea rows="8" cols="80" name="msg">Why are you denying this borrowing request?</textarea><br/><input type="submit" name="action" value="Confirm">';
  }
</script>

{% endblock %}

tools/templates/tools/szadmin.html
{% extends "tools/base.html" %}

{% block title %}Admin Page for {{ sz.name }}{% endblock %}

{% block content %}
<h1>{{ sz.name }}</h1>

<h2>Admins</h2>
{% for a in szAdmins %}
    <div class="display user admins">{{ a.user.first_name }} {{ a.user.last_name }}</div> <br/>
{% endfor %}

<h2>Unapproved Users</h2>
{% for u in unUsers %}
    <div class="display user unapproved">{{ u.user.first_name }} {{ u.user.last_name }}</div>
    <form action="{% url 'tools:approveUser' %}" method="POST">
      {% csrf_token %}
      <input type="hidden" name="userDataID" value="{{ u.id }}">
      <input type="submit" name="Status" value="Approve">
      <input type="submit" name="Status" value="Deny">
    </form><br/>
{% endfor %}

<h2>Users in ShareZone {{ sz.name }}</h2>
  {% for u in szUsers %}
  <div class="display user szone">{{ u.user.first_name }} {{ u.user.last_name }}</div>
    {% if u != userData %}
      <form action="{% url 'tools:administrateUser' %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="userDataID" value="{{ u.id }}">
        <br/><input type="submit" name="{{ u.id }}" value="Administrate">
      </form><br/>
    {% endif %}
{% endfor %}

<h2>Tools in ShareZone</h2>
{% for t in szTools %}
<p>
<div class="display szone tools">
    Name: {{ t.name }}<br/>
    Type: {{ t.toolType }}<br/>
    Owner: {{ t.owner.user.first_name }} {{ t.owner.user.last_name }}<br/>
    Home Location: {{ t.defaultLocation }}<br/>
    Current Location: {{ t.currentLocation }}<br/>
</div>
</p>
{% endfor %}
{% endblock %}

tools/templates/tools/toolview.html
{% extends "tools/base.html" %}

{% block title %}{{ Tool.name }}{% endblock %}

{% block content %}
<h1>{{ tool.name }}</h1>

<div class="container">
  <div class="row">
  
    <div class="col-md-12">
      <b>Type:</b> {{ tool.toolType }}
    </div>
    
    <div class="col-md-12">
      <b>Location:</b> {{ tool.currentLocation }}
    </div>

    <div class="col-md-12">
      <b>ShareZone:</b> {{ tool.defaultLocation.shareZone.name }}
    </div>

    <div class="col-md-12">
      <b>Condition:</b> {{ tool.condition }}
    </div>
    
    <div class="col-md-12">
      <b>Manufacturer:</b> {{ tool.manufacturer }}
    </div>
    
    <div class="col-md-12">
      <b>Status:</b> {{ status }}
    </div>
    
    <div class="col-md-12">
      <b>Additional Details:</b> {{ tool.additionalDetails }}
    </div>
    
    

    <div class="col-md-3">
      <form action="{% url 'tools:toolView' %}" method="POST">
{% csrf_token %}
        <input type="hidden" name="toolID" value="{{ tool.id }}">
{% if moveToShed %}
        <input type="submit" name="action" value="Move to Community Shed">
{% elif moveToHome %}
        <input type="submit" name="action" value="Move to your house">
{% endif %}
      </form>
    </div>

    <div class="col-md-3"> 
      <form action="{% url 'tools:showBorrowTool' %}" method="POST">
{% csrf_token %}
        <input type="hidden" name="toolID" value="{{tool.id}}">
        <input type="submit" name="action" value="Reserve this tool">
      </form> 
    </div>

    <div class="col-md-3">
      <form action="{% url 'tools:toolView' %}" method="POST">
{% csrf_token %}
        <input type="hidden" name="toolID" value="{{tool.id}}">
        {% if curReserv %}
        <input type="hidden" name="reservID" value="{{ curReserv.id }}">
        <input type="submit" name="action" value="Take this tool home">
{% endif %}
      </form>
    </div>
    
    <div class="col-md-3">
      <form action="{% url 'tools:toolView' %}" method="POST">
{% csrf_token %}
        <input type="hidden" name="toolID" value="{{tool.id}}">
{% if canReturn %}
        <input type="submit" name="action" value="Tool has been returned">
{% endif %}
      </form>
    </div>
    
    <div class="col-md-3">
      <form action="{% url 'tools:toolView' %}" method="POST">
{% csrf_token %}
        <input type="hidden" name="toolID" value="{{tool.id}}">
{% if canDel %}
        <input type="submit" name="action" value="De-register tool">
{% endif %}
      </form>
    </div>

    <div class="col-md-3">
{% if tReserv %}
  {% for r in tReserv %}
      <p>You have this tool reserved from {{ r.startDate }} until {{ r.endDate }}.</p>
  {% endfor %}
{% else %}
      <p>You have not yet reserved this tool.</p>
{% endif %}
    </div>


  </div>
</div>

{% endblock %}